changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New Features / Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Breaking Changes
      labels:
        - breaking
    - title: Non-Functional Changes
      labels:
        - "*"
